Repository gamemuncheol/gamemuncheol-frontend, pull requests merged in 2024-06, with the labels that each got.

#26 Feature/change linter formatter config
  .husky/pre-commit
  .pnp.cjs
  .prettierrc
  .prettierrc.js
  package.json
  yarn.lock
Labels: ⚡️ 간단

#34 next/image와 관련된 deprecated 설정을 업데이트 합니다.
  .gitignore
  next.config.mjs
Labels: 💨 Simple, ⚙️Config

#36 Navbar를 개선했습니다.
  package.json
  src/assets/menu/navbar/add.svg
  src/components/@common/navbar/Navbar.tsx
  src/components/@common/navbar/data/navGroups.ts
  src/components/@common/navbar/data/navList.ts
  src/components/@common/separator/Separator.tsx
  src/layout/LayoutProvider.tsx
  src/utils/.gitkeep
  src/utils/cn.ts
  src/utils/index.ts
  yarn.lock
Labels: 🎨Style, ⚡Feat

#41 로그인, 회원가입 관련해서 수정했습니다.
  src/components/@common/header/Header.tsx
  src/components/login/loginview/LoginView.tsx
  src/components/signup/nickname/Nickname.tsx
  src/components/signup/signupview/SignupView.tsx
  src/components/signup/useragree/UserAgree.tsx
  src/services/mutations/member.ts
  src/services/queries/member.ts
  src/services/queryKeys.ts
  src/store/useMemberStore.ts
  src/types/member-type.ts
Labels: 🎨Style, ⚡Feat
