Repository gamemuncheol/gamemuncheol-frontend, pull requests merged in 2024-07, with the labels that each got.

#43 사용자 정보를 요청하고 header에 사용자 프로필을 표시하였습니다.
  src/components/@common/header/Header.tsx
  src/services/queries/member.ts
  src/services/queryKeys.ts
  src/types/member-type.ts
Labels: ⚡Feat

#35 공통 모달 컴포넌트 수정 및 첫번째 등록 모달을 구현하였습니다.
  .vscode/extensions.json
  src/assets/common/Circle_Info_P.svg
  src/assets/index.ts
  src/assets/main/information.png
  src/assets/main/path.svg
  src/components/@common/modal/Modal.tsx
  src/components/@common/navbar/Navbar.tsx
  src/components/main/register/Register.tsx
  src/components/signup/nickname/Nickname.tsx
  src/components/signup/useragree/UserAgree.tsx
  src/types/common-type.ts
  videos/loginbg.mp4.json
Labels: 🎨Style, ⚡Feat

#44 #36 PR에서 Navbar 관련 리뷰 주신 내용을 반영 했습니다.
  src/components/@common/navbar/Navbar.tsx
  src/layout/LayoutProvider.tsx
Labels: 🎨Style
